# Generated by Django 4.2.13 on 2024-05-29 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("event_name", models.CharField(max_length=200)),
                (
                    "ticket_price_paid",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tickets_purchased", models.PositiveIntegerField()),
                ("date_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("surge_price_paid", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=200, unique=True)),
                (
                    "date_of_event",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("ticket_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_tickets", models.PositiveIntegerField()),
                ("available_tickets", models.PositiveIntegerField()),
            ],
        ),
    ]
