# Generated by Django 4.2.13 on 2024-05-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_date_of_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="place_of_event",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
