# Generated by Django 4.2.13 on 2024-05-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_place_of_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="place_of_event",
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(default="Mumbai", max_length=30),
        ),
    ]
