# Generated by Django 4.2.13 on 2024-05-29 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_remove_event_place_of_event_event_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
    ]
