# Generated by Django 4.2.13 on 2024-06-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_remove_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="place_of_event",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
