# Generated by Django 4.2.13 on 2024-06-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_event_place_of_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="place_of_event",
            field=models.CharField(default="No Location", max_length=50),
            preserve_default=False,
        ),
    ]
